import { useCallback, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { Button, Card, Label, Muted, Stat, Title } from '../../../components/ui';
import { MiniBarChart } from '../../../components/MiniBarChart';
import { colors, radius, spacing } from '../../../constants/theme';
import { supabase } from '../../../lib/supabase';
import { loadStudentEvolution, StudentEvolution } from '../../../lib/studentEvolution';
import { Profile, StudentAnamnesis, Workout } from '../../../lib/types';
import { Avatar } from '../../../components/Avatar';

export default function StudentDetail() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [student, setStudent] = useState<Profile | null>(null); const [workouts, setWorkouts] = useState<Workout[]>([]); const [anamnesis, setAnamnesis] = useState<StudentAnamnesis | null>(null); const [historyCount, setHistoryCount] = useState(0); const [evolution, setEvolution] = useState<StudentEvolution | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { if (!id) return; setLoading(true); const [profileResult, workoutsResult, anamnesisResult, historyResult] = await Promise.all([supabase.from('profiles').select('*').eq('id', id).maybeSingle(), supabase.from('workouts').select('*').eq('student_id', id).order('created_at', { ascending: false }), supabase.from('student_anamneses').select('*').eq('student_id', id).maybeSingle(), supabase.from('student_anamnesis_history').select('id', { count: 'exact', head: true }).eq('student_id', id)]); const currentAnamnesis = (anamnesisResult.data as StudentAnamnesis) ?? null; setStudent((profileResult.data as Profile) ?? null); setWorkouts((workoutsResult.data as Workout[]) ?? []); setAnamnesis(currentAnamnesis); setHistoryCount(historyResult.count ?? 0); setEvolution(await loadStudentEvolution(id, currentAnamnesis?.weight_kg)); setLoading(false); }, [id]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  if (loading) return <View style={styles.center}><ActivityIndicator color={colors.red} /></View>;
  if (!student) return <View style={styles.center}><Muted>Aluno não encontrado.</Muted></View>;
  const weightVariation = evolution?.weight.length && anamnesis?.weight_kg ? anamnesis.weight_kg - evolution.weight[0].value : 0;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />}>
    <Card style={styles.hero}><View style={styles.profileHeader}><Avatar name={student.full_name} value={student.avatar_url} size={76} /><View style={styles.profileInfo}><Title>{student.full_name}</Title><Text style={styles.goal}>{anamnesis?.goal || 'Objetivo não informado'}</Text><Muted>{student.streak_days} dia(s) de sequência · {workouts.length} treino(s) atribuídos</Muted></View></View></Card>
    <Button label="Criar novo treino" onPress={() => router.push({ pathname: '/(professor)/workout/new', params: { studentId: student.id } })} />
    {evolution?.isDemo ? <View style={styles.demo}><Text style={styles.demoTitle}>Dados de demonstração</Text><Muted>Este aluno ainda não possui sessões completas com cargas. Os gráficos abaixo são uma simulação e serão substituídos automaticamente pelos dados reais.</Muted></View> : null}
    <View style={styles.stats}><Stat value={anamnesis?.weight_kg ? `${anamnesis.weight_kg} kg` : '—'} label="Peso atual" /><Stat value={`${weightVariation > 0 ? '+' : ''}${weightVariation.toFixed(1)} kg`} label="Variação" /></View><View style={styles.stats}><Stat value={`${evolution?.completedSessions ?? 0}`} label="Treinos concluídos" /><Stat value={`${(evolution?.averageVolume ?? 0).toLocaleString('pt-BR')} kg`} label="Volume médio" /></View>
    <Label>Evolução</Label>{evolution?.weight.length ? <Card style={styles.section}><Text style={styles.sectionTitle}>Peso corporal</Text><MiniBarChart data={evolution.weight} suffix=" kg" /></Card> : <Card><Muted>Registre novos pesos na anamnese para acompanhar a evolução.</Muted></Card>}
    {evolution?.exercise ? <Card style={styles.section}><Text style={styles.sectionTitle}>Evolução de carga · {evolution.exercise.name}</Text><View style={styles.summary}><Muted>Inicial: {evolution.exercise.initial} kg</Muted><Muted>Atual: {evolution.exercise.current} kg</Muted><Text style={styles.positive}>{evolution.exercise.percent >= 0 ? '+' : ''}{evolution.exercise.percent}%</Text></View><MiniBarChart data={evolution.exercise.points} suffix=" kg" /></Card> : null}
    {evolution?.volume.length ? <Card style={styles.section}><Text style={styles.sectionTitle}>Volume movimentado</Text><Muted>Séries registradas × repetições × carga</Muted><MiniBarChart data={evolution.volume} suffix=" kg" /></Card> : null}
    <Label>Histórico</Label><Card style={styles.timeline}>{evolution?.timeline.length ? evolution.timeline.map((event, index) => <View key={event.id} style={styles.event}><View style={styles.marker}><View style={styles.dot} />{index < evolution.timeline.length - 1 ? <View style={styles.line} /> : null}</View><View style={styles.eventCopy}><Text style={styles.eventDate}>{event.date}</Text><Text style={styles.eventTitle}>{event.title}</Text><Muted>{event.detail}</Muted></View></View>) : <Muted>Nenhum acontecimento registrado.</Muted>}</Card>
    <Card style={styles.report}><Label>Avaliação e anamnese</Label>{anamnesis ? <View style={styles.reportContent}><Text style={styles.item}>Objetivo: {anamnesis.goal || 'Não informado'}</Text><Text style={styles.item}>Experiência: {anamnesis.experience_level || 'Não informada'}</Text><Text style={styles.item}>Altura/peso: {anamnesis.height_cm ? `${anamnesis.height_cm} cm` : '—'} / {anamnesis.weight_kg ? `${anamnesis.weight_kg} kg` : '—'}</Text><Text style={styles.item}>Condições de saúde: {anamnesis.health_conditions || 'Nenhuma informada'}</Text><Text style={styles.item}>Lesões ou dores: {anamnesis.injuries || 'Nenhuma informada'}</Text><Text style={styles.item}>Restrições: {anamnesis.exercise_restrictions || 'Nenhuma informada'}</Text><Muted>Atualizada em {new Date(anamnesis.updated_at).toLocaleDateString('pt-BR')}</Muted></View> : <Muted>Este aluno ainda não preencheu a anamnese.</Muted>}<Button label={`Ver histórico da anamnese (${historyCount})`} variant="ghost" onPress={() => router.push({ pathname: '/(professor)/student/history', params: { studentId: student.id } })} /></Card>
    <Label>Treinos</Label>{workouts.length ? workouts.map((workout) => <Card key={workout.id}><Text style={styles.workoutTitle}>{workout.title}</Text><Muted>{workout.duration_minutes} min · {workout.level}{workout.scheduled_for ? ` · ${workout.scheduled_for}` : ''}</Muted></Card>) : <Card><Muted>Nenhum treino criado para este aluno.</Muted></Card>}
  </ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.bg }, content: { width: '100%', maxWidth: 920, alignSelf: 'center', padding: spacing.lg, gap: spacing.md, paddingBottom: 48 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.bg }, hero: { backgroundColor: colors.surface }, profileHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, profileInfo: { flex: 1, minWidth: 0 }, goal: { color: colors.red, fontWeight: '800', marginVertical: 4 }, demo: { backgroundColor: '#FFF6D8', borderColor: '#E9CF70', borderWidth: 1, borderRadius: radius.md, padding: spacing.md, gap: 4 }, demoTitle: { color: '#725800', fontWeight: '900' }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, section: { gap: spacing.sm }, sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: '900' }, summary: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, positive: { color: colors.success, fontWeight: '900' }, timeline: { gap: 0 }, event: { flexDirection: 'row', gap: spacing.sm, minHeight: 76 }, marker: { width: 16, alignItems: 'center' }, dot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.red, marginTop: 4 }, line: { width: 2, flex: 1, backgroundColor: colors.border, marginVertical: 4 }, eventCopy: { flex: 1, paddingBottom: spacing.md }, eventDate: { color: colors.red, fontSize: 12, fontWeight: '900' }, eventTitle: { color: colors.ink, fontWeight: '800', marginVertical: 2 }, report: { gap: spacing.sm }, reportContent: { gap: 6 }, item: { color: colors.ink, fontSize: 14, lineHeight: 20 }, workoutTitle: { color: colors.ink, fontWeight: '800', fontSize: 16 } });
