import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Image, Linking, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, Card, Muted } from '../../../components/ui';
import { colors, spacing } from '../../../constants/theme';
import { supabase } from '../../../lib/supabase';
import { SetLog, WorkoutExercise, WorkoutSession } from '../../../lib/types';

const effortEmoji = (rating: number) => rating <= 2 ? '😌' : rating <= 4 ? '🙂' : rating <= 6 ? '😐' : rating <= 8 ? '😓' : '🥵';

export default function SessionScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [loading, setLoading] = useState(true); const [session, setSession] = useState<WorkoutSession | null>(null); const [exercises, setExercises] = useState<WorkoutExercise[]>([]); const [logs, setLogs] = useState<SetLog[]>([]); const [exerciseIndex, setExerciseIndex] = useState(0); const [saving, setSaving] = useState(false); const [ratingVisible, setRatingVisible] = useState(false); const [actualReps, setActualReps] = useState(''); const [actualWeight, setActualWeight] = useState('');
  useEffect(() => { async function load() { const { data: currentSession } = await supabase.from('workout_sessions').select('*').eq('id', id).maybeSingle(); if (!currentSession) { setLoading(false); return; } const sessionData = currentSession as WorkoutSession; setSession(sessionData); const [{ data: exerciseData }, { data: logData }] = await Promise.all([supabase.from('workout_exercises').select('*').eq('workout_id', sessionData.workout_id).order('sort_order'), supabase.from('set_logs').select('*').eq('session_id', sessionData.id)]); setExercises((exerciseData as WorkoutExercise[]) ?? []); setLogs((logData as SetLog[]) ?? []); setLoading(false); } load(); }, [id]);
  const current = exercises[exerciseIndex];
  useEffect(() => { if (current) { setActualReps(String(current.reps)); setActualWeight(String(current.target_weight_kg ?? 0)); } }, [current?.id]);
  const completedSets = useMemo(() => logs.filter((log) => log.exercise_id === current?.id).length, [logs, current?.id]);
  const totalVolume = useMemo(() => logs.reduce((sum, log) => sum + Number(log.reps) * Number(log.weight_kg), 0), [logs]);
  async function completeSet() { if (!session || !current) return; const reps = Number(actualReps); const weight = Number(actualWeight.replace(',', '.')); if (!Number.isInteger(reps) || reps <= 0 || !Number.isFinite(weight) || weight < 0) { Alert.alert('Confira a série', 'Informe repetições válidas e uma carga igual ou maior que zero.'); return; } const nextSet = completedSets + 1; if (nextSet > current.sets) return; setSaving(true); const { data, error } = await supabase.from('set_logs').insert({ session_id: session.id, exercise_id: current.id, set_number: nextSet, reps, weight_kg: weight }).select('*').single(); setSaving(false); if (error) { Alert.alert('Erro', error.message); return; } setLogs((previous) => [...previous, data as SetLog]); if (nextSet >= current.sets) { if (exerciseIndex < exercises.length - 1) setExerciseIndex((index) => index + 1); else setRatingVisible(true); } }
  async function finishSession(rating: number) { if (!session) return; setSaving(true); const { data: calculatedVolume } = await supabase.rpc('calculate_session_volume', { target_session: session.id }); const volume = Number(calculatedVolume ?? totalVolume); const { error } = await supabase.from('workout_sessions').update({ status: 'completed', finished_at: new Date().toISOString(), perceived_exertion: rating, total_volume_kg: volume }).eq('id', session.id); setSaving(false); if (error) { Alert.alert('Não foi possível concluir', error.message); return; } setRatingVisible(false); Alert.alert('Treino concluído', `Cansaço: ${rating}/10 ${effortEmoji(rating)}\nVolume total: ${volume.toLocaleString('pt-BR')} kg.`, [{ text: 'OK', onPress: () => router.replace('/(aluno)') }]); }
  if (loading) return <View style={styles.centered}><ActivityIndicator color="#fff" /></View>;
  if (!session || !current) return <SafeAreaView style={styles.safe}><Muted>Sessão inválida.</Muted><Button label="Voltar" onPress={() => router.back()} /></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><View style={styles.top}><Pressable onPress={() => router.back()}><Text style={styles.back}>Fechar</Text></Pressable><Text style={styles.progress}>Exercício {exerciseIndex + 1}/{exercises.length}</Text></View><View style={styles.body}>{current.image_url ? <Image source={{ uri: current.image_url }} style={styles.exerciseImage} /> : null}<Text style={styles.name}>{current.name}</Text><Text style={styles.setLabel}>Série {Math.min(completedSets + 1, current.sets)} de {current.sets}</Text><View style={styles.metrics}><Card style={styles.metric}><TextInput accessibilityLabel="Repetições realizadas" value={actualReps} onChangeText={setActualReps} keyboardType="number-pad" selectTextOnFocus style={styles.metricInput} /><Text style={styles.metricLabel}>REPETIÇÕES</Text></Card><Card style={styles.metric}><TextInput accessibilityLabel="Carga utilizada em quilos" value={actualWeight} onChangeText={setActualWeight} keyboardType="decimal-pad" selectTextOnFocus style={styles.metricInput} /><Text style={styles.metricLabel}>KG CARGA</Text></Card></View><Card style={styles.volumeCard}><Text style={styles.volumeLabel}>VOLUME ACUMULADO</Text><Text style={styles.volumeValue}>{totalVolume.toLocaleString('pt-BR')} kg</Text></Card>{current.video_url ? <Pressable onPress={() => Linking.openURL(current.video_url ?? '')}><Text style={styles.videoLink}>▶ Ver execução antes de começar</Text></Pressable> : null}</View><View style={styles.footer}><Button label={completedSets >= current.sets ? 'Próximo' : 'Concluir série'} onPress={completeSet} loading={saving} /><Button label="Finalizar treino" variant="ghost" onPress={() => setRatingVisible(true)} /></View><Modal visible={ratingVisible} transparent animationType="fade" onRequestClose={() => setRatingVisible(false)}><View style={styles.overlay}><Card style={styles.ratingCard}><Text style={styles.ratingTitle}>Como foi o cansaço?</Text><Muted>Avalie de 1 (muito leve) a 10 (exaustivo).</Muted><View style={styles.ratingGrid}>{Array.from({ length: 10 }, (_, index) => index + 1).map((rating) => <Pressable key={rating} accessibilityRole="button" accessibilityLabel={`Cansaço ${rating} de 10`} disabled={saving} onPress={() => finishSession(rating)} style={({ pressed }) => [styles.ratingButton, pressed && styles.ratingPressed]}><Text style={styles.ratingEmoji}>{effortEmoji(rating)}</Text><Text style={styles.ratingNumber}>{rating}</Text></Pressable>)}</View><Button label="Continuar treino" variant="ghost" onPress={() => setRatingVisible(false)} disabled={saving} /></Card></View></Modal></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.black, padding: spacing.lg }, centered: { flex: 1, backgroundColor: colors.black, alignItems: 'center', justifyContent: 'center' }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, back: { color: '#aaa', fontWeight: '600' }, progress: { color: '#fff', fontWeight: '700' }, body: { flex: 1, justifyContent: 'center', gap: spacing.md }, name: { color: '#fff', fontSize: 32, fontWeight: '800' }, setLabel: { color: colors.red, fontWeight: '700', fontSize: 16 }, metrics: { flexDirection: 'row', gap: 12 }, metric: { flex: 1, backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', alignItems: 'center' }, metricInput: { minWidth: 80, color: '#fff', fontSize: 28, fontWeight: '800', textAlign: 'center', borderBottomWidth: 1, borderBottomColor: '#555', paddingVertical: 2 }, metricLabel: { color: '#aaa', marginTop: 4, fontWeight: '700', fontSize: 12 }, volumeCard: { backgroundColor: '#171717', borderColor: '#333', alignItems: 'center' }, volumeLabel: { color: '#aaa', fontSize: 11, fontWeight: '800' }, volumeValue: { color: '#fff', fontSize: 24, fontWeight: '900', marginTop: 4 }, exerciseImage: { width: '100%', height: 170, borderRadius: 14 }, videoLink: { color: colors.red, fontWeight: '800', paddingTop: 4 }, footer: { gap: 10 }, overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.72)', justifyContent: 'center', padding: spacing.lg }, ratingCard: { width: '100%', maxWidth: 520, alignSelf: 'center', gap: spacing.md }, ratingTitle: { color: colors.ink, fontSize: 24, fontWeight: '900' }, ratingGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: spacing.xs }, ratingButton: { width: 58, minHeight: 70, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.secondary, alignItems: 'center', justifyContent: 'center' }, ratingPressed: { borderColor: colors.red, backgroundColor: colors.redSoft }, ratingEmoji: { fontSize: 25 }, ratingNumber: { color: colors.ink, fontWeight: '900', marginTop: 3 } });
