import { useCallback, useState } from 'react';
import { Alert, FlatList, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { Button, Card, Input, Label, Muted, Title } from '../../components/ui';
import { colors, spacing } from '../../constants/theme';
import { useAuth } from '../../contexts/AuthContext';
import { supabase } from '../../lib/supabase';
const days = ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
export default function ProfessorAgenda() { const { profile } = useAuth(); const [day,setDay]=useState('1'); const [start,setStart]=useState('08:00'); const [end,setEnd]=useState('09:00'); const [slots,setSlots]=useState<any[]>([]); const [appointments,setAppointments]=useState<any[]>([]); const load=useCallback(async()=>{if(!profile)return; const [a,b]=await Promise.all([supabase.from('coach_availability').select('*').eq('coach_id',profile.id).eq('active',true).order('day_of_week'),supabase.from('appointments').select('*, student:profiles!appointments_student_id_fkey(full_name, avatar_url)').eq('coach_id',profile.id).order('starts_at')]);setSlots(a.data??[]);setAppointments(b.data??[]);},[profile]);useFocusEffect(useCallback(()=>{load()},[load]));async function add(){if(!profile)return;const {error}=await supabase.from('coach_availability').insert({coach_id:profile.id,day_of_week:Number(day),start_time:start,end_time:end});if(error)Alert.alert('Erro',error.message);else load()}async function status(id:string,value:string){await supabase.from('appointments').update({status:value}).eq('id',id);load()}return <FlatList data={appointments} keyExtractor={i=>i.id} ListHeaderComponent={<View style={styles.header}><Label>Agenda do professor</Label><Title>Horários e consultas</Title><Card style={styles.card}><Muted>Cadastre um horário recorrente da semana. Você pode ajustar a data válida no banco depois.</Muted><Input placeholder="Dia (0 domingo a 6 sábado)" value={day} onChangeText={setDay} keyboardType="number-pad"/><Input placeholder="Início (08:00)" value={start} onChangeText={setStart}/><Input placeholder="Fim (09:00)" value={end} onChangeText={setEnd}/><Button label="Adicionar horário" onPress={add}/></Card><Label>Disponibilidade</Label>{slots.map(s=><Card key={s.id}><Text style={styles.bold}>{days[s.day_of_week]} · {String(s.start_time).slice(0,5)}–{String(s.end_time).slice(0,5)}</Text></Card>)}<Label>Solicitações</Label></View>} renderItem={({item})=><Card style={styles.card}><Text style={styles.bold}>{item.student?.full_name ?? 'Aluno'} · {new Date(item.starts_at).toLocaleString('pt-BR')}</Text><Muted>Status: {item.status}</Muted>{item.status==='requested'&&<Button label="Confirmar" onPress={()=>status(item.id,'confirmed')}/>}</Card>} ListEmptyComponent={<Muted>Nenhum agendamento ainda.</Muted>} contentContainerStyle={styles.content}/>}
const styles=StyleSheet.create({content:{padding:spacing.lg,gap:spacing.sm,backgroundColor:colors.bg},header:{gap:spacing.md},card:{gap:8},bold:{fontWeight:'800',color:colors.ink}});
